version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/todo_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_APP_URL: http://localhost:3000
      REACT_APP_BACKEND_URL: http://localhost:8080/api/tasks

volumes:
  postgres_data:
